### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method setForeground() 

### ISSUE THREAD

**Issue by FennyR** [Kotlin/anko#365]
java.lang.NoSuchMethodError: No virtual method setForeground(Landroid/graphics/drawable/Drawable;)V in class Landroid/view/View; or its super classes (declaration of 'android.view.View' appears in /system/framework/framework.jar)
 is failing in Android 5.0 version. It is working fine in Android 6.0 and above

**Comment by yanex** [comment]
Can you please attach the complete stack trace?

**Comment by FennyR** [comment]
I am trying to use the method setForeground() on a view.
But according to the Android documentation, setForeground() on a regular view is available form API level 23. Where as the method is avaialble for FrameLayout since API level 1.
My intention is to setForeground to a FrameLayout.

below is how I set it for a FrameLayout:

((FrameLayout)activity.findViewById(R.id.container_body)).setForeground(activity.getResources().getDrawable(R.drawable.foreground_for_popup));

**Comment by yanex** [comment]
I can't find the `setForeground()` method for `FrameLayout` here: https://developer.android.com/reference/android/widget/FrameLayout.html.

**Comment by FennyR** [comment]
Sorry, it is an typo.
The method is setForeground (Drawable drawable)

https://developer.android.com/reference/android/view/View.html#setForeground(android.graphics.drawable.Drawable)


Thanks,
Fenny.

**Comment by yanex** [comment]
Turns out you're not the first who asks this question :) https://github.com/Kotlin/anko/issues/220
